### ISSUE TITLE
unable to build on windows

### ISSUE THREAD

**Issue by n00kii** [imxood/small-player#2]
after following steps in `README.md`, arrived at this error when trying to build
```
error: linking with `rust-lld.exe` failed: exit code: 1

...
/* omitted long list of paths */
...

  = note: rust-lld: error: undefined symbol: IID_ICodecAPI
          >>> referenced by C:\Users\Moruph\vcpkg\buildtrees\ffmpeg\src\n4.4.1-9dd22c1484.clean\libavcodec\mfenc.c:1068
          >>>               avcodec.lib(mfenc.o):(mf_init)

          rust-lld: error: undefined symbol: IID_IMFMediaEventGenerator
          >>> referenced by C:\Users\Moruph\vcpkg\buildtrees\ffmpeg\src\n4.4.1-9dd22c1484.clean\libavcodec\mfenc.c:996
          >>>               avcodec.lib(mfenc.o):(mf_unlock_async)

          rust-lld: error: undefined symbol: IID_IMFTransform
          >>> referenced by C:\Users\Moruph\vcpkg\buildtrees\ffmpeg\src\n4.4.1-9dd22c1484.clean\libavcodec\mf_utils.c:633
          >>>               avcodec.lib(mf_utils.o):($LN56)


warning: `small-player` (bin "small-player") generated 22 warnings
error: could not compile `small-player` due to previous error; 22 warnings emitted
```

**Comment by imxood** [comment]
Hi,  you can get the lastest code, try again~ it should is ok.

**Comment by n00kii** [comment]
it works now but i have to change the fonts
```
2022-11-16T03:14:37.084552Z  INFO small_player::resources::fonts: FontFamily::Proportional:
2022-11-16T03:14:37.084656Z  INFO small_player::resources::fonts:       chinese
thread 'main' panicked at 'Failed to find replacement characters '◻' or '?'', C:\Users\Moruph\.cargo\registry\src\github.com-1ecc6299db9ec823\epaint-0.19.0\src\text\font.rs:258:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-11-16T03:14:37.100038Z  INFO small_player::services::player::player: Player Dropped
error: process didn't exit successfully: `target\debug\small-player.exe` (exit code: 101)
```

**Comment by imxood** [comment]
> it works now but i have to change the fonts
> 
> ```
> 2022-11-16T03:14:37.084552Z  INFO small_player::resources::fonts: FontFamily::Proportional:
> 2022-11-16T03:14:37.084656Z  INFO small_player::resources::fonts:       chinese
> thread 'main' panicked at 'Failed to find replacement characters '◻' or '?'', C:\Users\Moruph\.cargo\registry\src\github.com-1ecc6299db9ec823\epaint-0.19.0\src\text\font.rs:258:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 2022-11-16T03:14:37.100038Z  INFO small_player::services::player::player: Player Dropped
> error: process didn't exit successfully: `target\debug\small-player.exe` (exit code: 101)
> ```

Can you show your code?
